#!/usr/bin/env bash

## Copies active config to version folder
##
## Usage: fin brush [params to passthrough]
cd ${PROJECT_ROOT}

  case "$1" in 
    a ) FROM="active";
    ;;
    s ) FROM="staging";
    ;;
    v ) FROM="versioned";
    ;;
    * ) FROM="active";
    ;;
  esac

  case "$2" in 
    a ) TO="active";
    ;;
    s ) TO="staging";
    ;;
    v ) TO="versioned";
    ;;
    * ) TO="versioned";
    ;;
  esac

  echo -e
  echo "This will copy the config from ${FROM} to ${TO} , ";
  read -p "Continue (y/n)?" choice
    case "$choice" in 
      y|Y ) echo "Fair Enough, let's continue!";;
      n|N ) echo "Exiting"; exit;;
      * ) echo "invalid";;
    esac

  FILES=(/var/www/config/"$TO"/*.json);
  if [ -e "${files-}" ];
  then
    fin exec rm ${FILES}
  fi
  fin exec rsync -v config/"$FROM"/*.json config/"$TO"
