#!/usr/bin/env bash

## Copies active config to version folder
##
## Usage: fin brush [params to passthrough]
cd ${PROJECT_ROOT}
if [ -n "$2" ]; then
  case "$1" in 
    a ) FROM="active";
    ;;
    s ) FROM="staging";
    ;;
    v ) FROM="versioned";
    ;;
    * ) echo "a for active
              s for staging
              v for versioned"; exit;;
  esac

  case "$2" in 
    a ) TO="active";
    ;;
    s ) TO="staging";
    ;;
    v ) TO="versioned";
    ;;
    * ) echo "a for active
              s for staging
              v for versioned"; exit;;
  esac

  echo -e
  echo "This will copy the config from "${PROJECT_ROOT}/${1}" to "${PROJECT_ROOT}/${2}".";
  read -p "Continue (y/n)?" choice
    case "$choice" in 
      y|Y ) echo "Fair Enough, let's continue!";;
      n|N ) echo "Exiting"; exit;;
      * ) echo "invalid";;
    esac

fin exec cp -v ${PROJECT_ROOT}/config/"$1"/*.json ${PROJECT_ROOT}/config/"$2"

else
  echo "
  Forget Something? like 
  'config a v'
  a for active
  s for staging
  v for versioned
  "
fi
