#!/usr/bin/env bash
## drush uli - User login substitute
##
## Usage: fin uli
# Abort if anything fails
set -e
# SETTINGS
# Either uncommend out the following line, or set in docksal-local.env
# SITE_URI="newupstream.docksal"
fin drush uli "$@" --uri=${VIRTUAL_HOST}